--!strict

--- ### hula.luauㅤ/ˈhuːlə/
---
--- a table of roblox-luau convenience modules \
--- [*view hula on github*](https://github.com/00826/hula)
return table.freeze{
	color3 = require(script:WaitForChild("color3"));
	gui = require(script:WaitForChild("gui"));
	inputs = require(script:WaitForChild("inputs"));
	instance = require(script:WaitForChild("instance"));
	math = require(script:WaitForChild("math"));
	net = require(script:WaitForChild("net"));
	patronage = require(script:WaitForChild("patronage"));
	types = require(script:WaitForChild("types"));
	vector3 = require(script:WaitForChild("vector3"));
}