--!strict

--- ### hula.luauㅤ/ˈhuːlə/
---
--- a table of roblox-luau convenience modules \
--- [*view hula on github*](https://github.com/00826/hula)
return table.freeze{
	color3h = require(script:WaitForChild("color3h"));
	gui = require(script:WaitForChild("gui"));
	inputs = require(script:WaitForChild("inputs"));
	instanceh = require(script:WaitForChild("instanceh"));
	mathh = require(script:WaitForChild("mathh"));
	net = require(script:WaitForChild("net"));
	patronage = require(script:WaitForChild("patronage"));
	types = require(script:WaitForChild("types"));
	vector3h = require(script:WaitForChild("vector3h"));
}