--!strict

--- ### hula.luauㅤ/ˈhuːlə/
---
--- a table of roblox-luau convenience modules \
--- [*view hula on github*](https://github.com/00826/hula)
return table.freeze{
	bufferh = require(script.bufferh);
	color3h = require(script.color3h);
	gui = require(script.gui);
	inputs = require(script.inputs);
	instanceh = require(script.instanceh);
	mathh = require(script.mathh);
	net = require(script.net);
	patronage = require(script.patronage);
	stringh = require(script.stringh);
	tableh = require(script.tableh);
	vector3h = require(script.vector3h);
}